select_origin: directory
files_origin: ./content
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ./images
export_target: ./export/
history: false
focus_max: 2
record_types:
  undefined:
    fill: "#858585"
    stroke: "#858585"
  about:
    fill: "#984ea3"
    stroke: "#984ea3"
link_types:
  undefined:
    stroke: simple
    color: "#e1e1e1"
references_as_nodes: false
references_type_label: references
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 10
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 20
node_size_min: 2
attraction_force: 200
attraction_distance_max: 250
attraction_vertical: 0
attraction_horizontal: 0
views: {}
record_metas: []
generate_id: never
link_context: tooltip
hide_id_from_record_header: true
title: "Dr Ben Denham"
author: "Ben Denham"
description: "Testing"
keywords: []
link_symbol: ""
csl: "bib/apa.csl"
bibliography: "bib/bib.json"
csl_locale: "bib/locales-en-GB.xml"
css_custom: "custom.css"
devtools: true
lang: en
